# Another project management software
# Copyright (C) 2021 Salah OSFOR <osfor.salah@gmail.com>

version: "3.3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pigmalion}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apassword}
      PGDATA: /opt/volums/pg_train
    volumes:
       - postgres:/opt/volums/pg_train
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes: 
  postgres:
