# Another project management software
# Copyright (C) 2021 Salah OSFOR <osfor.salah@gmail.com>

version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-pigmalion}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-apassword}
      PGDATA: /opt/volums/pg_quadriga
    volumes:
       - postgres:/opt/volums/pg_quadriga
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    restart: unless-stopped
  core:
    build: core/
    environment: 
      DEBUG: true
      DB_NAME: ${DB_NAME:-pigmalion}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-apassword}
      DB_PORT: ${DB_PORT:-5432}
      DB_HOST: ${DB_HOST:-db}
    command: tail -f /dev/null
    ports:
      - "${CORE_PORT:-8080}:${CORE_PORT:-8080}"
    volumes: 
      - ./core/:/api
    depends_on:
      - db
    restart: unless-stopped

volumes: 
  postgres:
  core:
