version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  prepare:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: core/requirements.txt
          pkg-manager: pip
      - run:
          command: |
            flake8 --version
          name: Flake8 version

workflows:
  setup:
    jobs:
      - prepare
