version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  linting:
    executor: python/default
    steps:
      - checkout
      - run: pip install -r dev-requirements.txt
      - run:
          command: flake8 --ignore=E501 core/
          name: linting-core

workflows:
  setup:
    jobs:
      - linting
