# This is a basic workflow to help you get started with Actions

name: CI-TESTS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "Not a secret"
      DEBUG: 1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies GLOBAL
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Install dependencies CORE
        run: pip install -r core/requirements.txt
      - name: checking linting "CORE"
        run: flake8 --ignore=E501,F401 core/
      - name: unit tests "CORE"
        run: python core/manage.py test
